name: Fetch and Store Market Data

on: 
  schedule: 
    - cron: '*/15 * * * 1-5'  # Alle 15 Minuten, Montag bis Freitag workflow_dispatch:         # Manuelles Starten zulassen

jobs: 
  fetch-and-store: 
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3
    
      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
    
      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Skript ausführen
        env:
          TWELVE_API_KEY: ${{ secrets.TWELVE_API_KEY }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python main.py
    
      - name: Ergebnis als Artifact speichern
        uses: actions/upload-artifact@v3
        with:
          name: marketdata-json
          path: '*.json'

