name: Fetch and Store Market Data

on:
  schedule:
    - cron: '*/15 * * * 1-5'
  workflow_dispatch:

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.4

      - name: Setup Python
        uses: actions/setup-python@v4.8.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          TWELVE_API_KEY: ${{ secrets.TWELVE_API_KEY }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python main.py

      - name: Upload JSON result
        uses: actions/upload-artifact@v3.1.3
        with:
          name: marketdata-json
          path: '*.json'
